apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-java-web-app-kaniko
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
    apps.tanzu.vmware.com/act-tests: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app-kaniko
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
      apps.tanzu.vmware.com/act-tests: "true"
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: tanzu-java-web-app-kaniko
  template:
    metadata:
      annotations:
        apps.tanzu.vmware.com/debug: "true"
        apps.tanzu.vmware.com/live-update: "true"
        conventions.carto.run/applied-conventions: |-
          appliveview-sample/app-live-view-appflavour-check
          developer-conventions/add-source-image-label
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
        apps.tanzu.vmware.com/act-tests: "true"
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: tanzu-java-web-app-kaniko
    spec:
      containers:
      - env:
        - name: JAVA_TOOL_OPTIONS
          value: -javaagent:/var/tmp/elastic-apm-agent-1.38.1-20230512.153148-12.jar -Delastic.apm.application_packages="org.example,org.another.example" -Delastic.apm.server_url="http://127.0.0.1:8200" -Delastic.apm.service_name="my-cool-service"
        image: harbor.lab.tw/tap-ap/tanzu-java-web-app-kaniko-tap-sit@sha256:17ab6b9c5177e3fa8c5b0f7bcbab81b96db9629ea1f6adb21084fa7172dacc7d
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: workload-sa
---
apiVersion: v1
kind: Service
metadata:
  name: tanzu-java-web-app-kaniko
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
    apps.tanzu.vmware.com/act-tests: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app-kaniko
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
    apps.tanzu.vmware.com/act-tests: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: tanzu-java-web-app-kaniko
  ports:
  - targetPort: 8080
    port: 8080
    name: http

