apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-java-web-app-kaniko
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
    ootb.apps.tanzu.vmware.com/servicebinding-workload: "true"
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
    apps.tanzu.vmware.com/act-tests: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app-kaniko
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: run
      app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
      apps.tanzu.vmware.com/act-tests: "true"
      apps.tanzu.vmware.com/has-tests: "true"
      apps.tanzu.vmware.com/workload-type: server
      carto.run/workload-name: tanzu-java-web-app-kaniko
  template:
    metadata:
      annotations:
        conventions.carto.run/applied-conventions: |-
          spring-boot-convention/auto-configure-actuators-check
          spring-boot-convention/app-live-view-appflavour-check
          appliveview-sample/app-live-view-appflavour-check
        developer.conventions/target-containers: workload
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"tanzu-java-web-app-kaniko","apps.tanzu.vmware.com/act-tests":"true","apps.tanzu.vmware.com/has-tests":"true","apps.tanzu.vmware.com/workload-type":"server"},"name":"tanzu-java-web-app-kaniko","namespace":"tap-sit"},"spec":{"params":[{"name":"dockerfile","value":"./Dockerfile"},{"name":"buildServiceBindings","value":[{"kind":"Secret","name":"elastic-apm"}]},{"name":"scanning_source_policy","value":"scan-policy"},{"name":"actest-namespace","value":"tap-delivery"},{"name":"testing_pipeline_matching_labels","value":{"apps.tanzu.vmware.com/pipeline":"vmware-approvaltask"}},{"name":"integration_testing_matching_labels","value":{"apps.tanzu.vmware.com/pipeline":"int-test"}}],"source":{"git":{"ref":{"branch":"dev"},"url":"https://github.com/timwangvmw/tanzu-java-web-app133.git"}}}}
      labels:
        app.kubernetes.io/component: run
        app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
        apps.tanzu.vmware.com/act-tests: "true"
        apps.tanzu.vmware.com/has-tests: "true"
        apps.tanzu.vmware.com/workload-type: server
        carto.run/workload-name: tanzu-java-web-app-kaniko
    spec:
      containers:
      - image: harbor.lab.tw/tap-ap/tanzu-java-web-app-kaniko-tap-sit@sha256:a899192d864e6ba49e7bb6506221e46361c9a9ede22825166da667daf7487c0a
        name: workload
        resources: {}
        securityContext:
          runAsUser: 1000
      serviceAccountName: workload-sa
---
apiVersion: v1
kind: Service
metadata:
  name: tanzu-java-web-app-kaniko
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
    apps.tanzu.vmware.com/act-tests: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-app-kaniko
spec:
  selector:
    app.kubernetes.io/component: run
    app.kubernetes.io/part-of: tanzu-java-web-app-kaniko
    apps.tanzu.vmware.com/act-tests: "true"
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: server
    carto.run/workload-name: tanzu-java-web-app-kaniko
  ports:
  - targetPort: 8080
    port: 8080
    name: http

