apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-demo-app
  namespace: tap-sit
  labels:
    app.kubernetes.io/part-of: helm-demo-app
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/component: helm-release
    app.tanzu.vmware.com/release-type: helm
spec:
  interval: 5m
  chart:
    spec:
      chart: tap
      sourceRef:
        kind: HelmRepository
        name: timwang-github
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    workloadname: helm-demo-app
    image:
      repository: harbor.lab.tw/tap-ap/helm-demo-app-tap-sit@sha256:7be4b29bc1dc2ed8693a14c4c9ffb3d46030b185f8923d6263373026b82c30ce

