apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-demo-app
  namespace: tap-sit
  labels:
    app.kubernetes.io/part-of: helm-demo-app
    app.kubernetes.io/component: helm-release
    app.tanzu.vmware.com/release-type: helm
spec:
  interval: 5m
  chart:
    spec:
      chart: tap
      sourceRef:
        kind: HelmRepository
        name: timwang-github
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
    workloadname: helm-demo-app
    image:
      repository: harbor.lab.tw/tap-ap/helm-demo-app-tap-sit@sha256:2ff10d209f6600d7c6629c2bab0441eafd9990249a1cf3d733e87c03229722a5

